version: "3.9"
services:
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: "library"
        POSTGRES_USER: "user"
        POSTGRES_HOST: "localhost"
        POSTGRES_PASSWORD: "password"
        PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      ports:
        - "5432:5432"
      restart: unless-stopped